### ISSUE TITLE
ts-typed-sql

### ISSUE THREAD

**Issue by hediet** [Ff00ff/db#1]
Hi there!
I am the author of [ts-typed-sql](https://github.com/hediet/ts-typed-sql).
Maybe we can join efforts? Currently I have some bugs to fix in my library, but due to my studies, I am missing time to fix them.

**Comment by martijndeh** [comment]
Great work on typed-sql! There indeed seems overlap. I'll reach out through email so we can discuss.

**Comment by sledorze** [comment]
@martijndeh @hediet would love to know if you've decided onto something..

**Comment by hediet** [comment]
@sledorze We both will continue to support our own library. At the current time, mine seems to be much more feature complete (in particular due to the fact that I have fully featured expression and query trees) but my library is missing migrations and code generation. Once my library is stable enough and I came up with a solution to how I deal with runtime types, I will publish and promote it independently from this library.

**Comment by sledorze** [comment]
@hediet ok understand, maybe those high quality FP libs could help:

https://github.com/gcanti/io-ts
https://github.com/gcanti/io-ts-codegen

There's a whole ecosystem https://github.com/gcanti?tab=repositories
